### PR TITLE
Home Page for the newsweek.com built with HTML, CSS and bootstrap

### PR DESCRIPTION
**Pull request by mbabaliiryn**
# A home page for the newsweek.com built with HTML, CSS and bootstrap.

### CODE REVIEW

**Comment by euqueme** [comment]
Hello @mbabaliiryn :wave: 

I have to invalidate your project as it has to have a descriptive PR :v: 

Do this change and submit back for a code review

**Comment by euqueme** [comment]
Hello @mbabaliiryn :wave: 

Kindly edit the PR and provide a description as I can't start reviewing without it :point_down: 

image

Do the change and submit back for a code review

**Comment by mbabaliiryn** [comment]
Hello TSE,
I accidentally submitted to a wrong project but I was supposed to request
code review for bootstrap project.

Can that be corrected?

Regards,

NANYONJO IRENE,
0758323723,
mbabaliiryn@gmail.com,
Kisaasi - Kampala.

**Comment by addod19** [comment]
Hi @mbabaliiryn, can you Kindly enable stickler for your repo? I cannot start reviewing without it. To enable stickler visit https://stickler-ci.com/

**Comment by addod19** [comment]
## Pull Request under Review by Daniel Larbi Addo (TSE)

**Comment by mbabaliiryn** [comment]
Hey Raymond,

Thanks so much for reviewing my code in time.
I have done all the required changes and I have submitted back my code for
approval.

Regards,

NANYONJO IRENE,
0758323723,
mbabaliiryn@gmail.com,
Kisaasi - Kampala.

**Pull request merged**
